apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.6
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: keycloak-certs
              mountPath: /etc/keycloak/certs
            - name: keycloak-themes
              mountPath: /opt/keycloak/themes
            - name: keycloak-config
              mountPath: /opt/keycloak/standalone/configuration
          readinessProbe:
            httpGet:
              path: /realms/master
              port: 8080
      volumes:
        - name: keycloak-certs
          persistentVolumeClaim:
            claimName: keycloak-certs-pvc
        - name: keycloak-themes
          persistentVolumeClaim:
            claimName: keycloak-themes-pvc
        - name: keycloak-config
          persistentVolumeClaim:
            claimName: keycloak-config-pvc