apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: keycloak
          image: harbor.rr.sebrae.com.br/keycloak/keycloak26:v1.0.0
          args: ["start", "--https-key-store-file=/etc/keycloak/certs/keycloak.jks", "--https-key-store-password=$(KC_KEYSTORE_PASSWORD)"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://10.23.4.92:5432/keycloak-prod"
            - name: KC_HOSTNAME
              value: "10.23.6.22"
            - name: KC_HOSTNAME_STRICT_HTTPS
              value: "true"            
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: password
            - name: KC_KEYSTORE_FILE
              value: "/etc/keycloak/certs/keycloak.jks"
            - name: KC_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-https-cert
                  key: password.txt
          volumeMounts:
              - name: keycloak-certs
                mountPath: /etc/keycloak/certs
                readOnly: true

          ports:
            - name: https
              containerPort: 8443
      volumes:
        - name: keycloak-certs
          secret:
            secretName: keycloak-https-cert