apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.6
          args: ["start-dev"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "admin"
            - name: KC_PROXY
              value: "edge"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://10.23.4.92:5432/keycloak-prod"
            - name: KC_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: username
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-credentials
                  key: password
            - name: KC_KEYSTORE_FILE
              value: "/etc/keycloak/certs/keycloak.jks"
            - name: KC_KEYSTORE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-https-cert
                  key: password.txt
          volumeMounts:
              - name: keycloak-certs
                mountPath: /etc/keycloak/certs
                readOnly: true

          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
