apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-credentials
  namespace: keycloak
type: Opaque
data:
  username: a2V5Y2xvYWs= # Base64 de 'keycloak'
  password: aXBSPE0+SCN4TFdtfg== # Base64 da password
