apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-theme-pvc
  namespace: keycloak
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
