apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorteador-server
  namespace: sorteador
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sorteador
  template:
    metadata:
      labels:
        app: sorteador
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: sorteador-server
          image: harbor.rr.sebrae.com.br/sorteador/sorteador:v1.0.2
          ports:
            - containerPort: 5000
