apiVersion: v1
kind: Service
metadata:
  name: apisebrae-service
  namespace: apisebrae-homolog
spec:
  type: LoadBalancer
  selector:
    app: apisebrae
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: admin
      port: 9990
      targetPort: 9990
