# Copyright (C) 2019, Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Wazuh StorageClass

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: wazuh-storage
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3" # Número de réplicas para alta disponibilidade
  staleReplicaTimeout: "30" # Tempo limite para réplicas obsoletas (em minutos)
  fromBackup: "" # (Opcional) Cria o volume a partir de um backup Longhorn
allowVolumeExpansion: true # Permitir a expansão do volume
reclaimPolicy: Retain # (Opcional) Política de retenção dos volumes: Retain ou Delete
volumeBindingMode: WaitForFirstConsumer # (Opcional) Atrasar a criação do volume até que ele seja vinculado a um Pod


# In case you're running Minikube you can comment the line above and use this one
# provisioner: k8s.io/minikube-hostpath

# If you're using a different provider you can list storage classes
# with: "kubectl get sc" and look for the column "Provisioner"
