apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      containers:
        - name: wazuh-agent
          image: kennyopennix/wazuh-agent:4.7.2
          securityContext:
            privileged: true
          env:
            - name: JOIN_MANAGER_MASTER_HOST
              value: "wazuh.wazuh.svc.cluster.local"
            - name: JOIN_MANAGER_WORKER_HOST
              value: "wazuh-workers.wazuh.wazuh.svc.cluster.local"
            - name: JOIN_MANAGER_PROTOCOL
              value: "https"
            - name: WAZUH_GROUPS
              value: kubernetes-nodes
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: JOIN_MANAGER_USER
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: username
            - name: JOIN_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred
                  key: password
            - name: JOIN_MANAGER_API_PORT
              value: "55000"
            - name: JOIN_MANAGER_PORT
              value: "1514"
