apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: wazuh-agent
  namespace: wazuh
  labels:
    app: wazuh-agent
spec:
  selector:
    matchLabels:
      app: wazuh-agent
  template:
    metadata:
      labels:
        app: wazuh-agent
    spec:
      containers:
        - name: wazuh-agent
          image: kennyopennix/wazuh-agent:4.0.4
          securityContext:
            privileged: true
            env:
            - name: JOIN_MANAGER_MASTER_HOST
              value: "wazuh.wazuh.svc.cluster.local"  # Endereço do servidor principal do Wazuh
            - name: JOIN_MANAGER_WORKER_HOST
              value: "wazuh-workers.wazuh.svc.cluster.local"  # Endereço do servidor de trabalho do Wazuh
            - name: JOIN_MANAGER_PROTOCOL
              value: "https"  # Protocolo de comunicação
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName  # Nome do nó onde o agente está sendo executado
            - name: JOIN_MANAGER_USER
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred  # Referência ao segredo contendo o nome de usuário
                  key: username  # Chave para o nome de usuário
            - name: JOIN_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wazuh-api-cred  # Referência ao segredo contendo a senha
                  key: password  # Chave para a senha
            - name: JOIN_MANAGER_API_PORT
              value: "55000"  # Porta da API do Wazuh
            - name: JOIN_MANAGER_PORT
              value: "1514"  # Porta do agente Wazuh
      restartPolicy: Always
