apiVersion: apps/v1
kind: Deployment
metadata:
  name: sistema-avaliacao
  namespace: sistema-avaliacao-homolog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sistema-avaliacao
  template:
    metadata:
      labels:
        app: sistema-avaliacao
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: sistema-avaliacao
          image: harbor.rr.sebrae.com.br/sistema-avaliacao-homolog/sistema-avaliacao:v1.0.15
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: SCRIPT_NAME
              value: script-ssl.sh
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: laravel-env-volume
              mountPath: /var/www/html/.env
              subPath: .env
          resources:
            requests:
              memory: "200Mi"
              cpu: "3m"
      volumes:
        - name: laravel-env-volume
          configMap:
            name: laravel-staging-env
        - name: tls-secret
          secret:
            secretName: ssl-sebrae
