apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: consulta-jucerr-ingressroute
  namespace: consulta-jucerr-homolog
spec:
  entryPoints:
    - websecure                                  
  routes:
    - match: Host(`sistemavaliacao-homolog.rr.sebrae.com.br`)
      kind: Rule
      services:
        - name: sistema-avaliacao-service
          kind: Service
          namespace: sistema-avaliacao-homolog
          port: 80
          scheme: http
  tls:
    secretName: ssl-sebrae
