apiVersion: v1
kind: Service
metadata:
  name: sistema-avaliacao-service
  namespace: sistema-avaliacao-homolog
spec:
  type: LoadBalancer
  selector:
    app: sistema-avaliacao
  ports:
    - name: https
      port: 443
      targetPort: 443
