apiVersion: v1
kind: Service
metadata:
  name: sistema-avaliacao-service
  namespace: sistema-avaliacao-homolog
spec:
  type: ClusterIP
  selector:
    app: sistema-avaliacao
  ports:
    - name: http
      port: 80
      targetPort: 80
