apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/ansible/awx-operator/config/default?ref=2.18.0
  - resources/awx-ubuntu.yml
  - resources/secret-pgsql.yaml
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.18.0

namespace: awx
