apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: devops-tools
spec:
  selector:
    app: jenkins-server
  type: LoadBalancer
  ports:
    - name: https   # Nome da porta HTTPS
      port: 443
      targetPort: 8443
    - name: http    # Nome da porta HTTP
      port: 80
      targetPort: 8080
