apiVersion: apps/v1
kind: Deployment
metadata:
  name: facilita
  namespace: facilita-homolog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: facilita
  template:
    metadata:
      labels:
        app: facilita
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: apache-facilita
          image: harbor.rr.sebrae.com.br/sebrae.rr.facilita.homolog/facilita:v1.0.12
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes:
        - name: tls-secret
          secret:
            secretName: ssl-sebrae

