kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik

spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v3.2
          args:
            - --api.insecure
            - --providers.kubernetesingress
            - --entryPoints.web.address=:80
            - --entryPoints.websecure.address=:443
            - --entryPoints.web.proxyProtocol.insecure
            - --providers.kubernetescrd.certauthfilepath=/certs/ca.crt
          ports:
            - name: web
              containerPort: 80
            - name: dashboard
              containerPort: 8080
            - name: websecure
              containerPort: 443
          volumeMounts:
            - name: certs-volume
              mountPath: /certs
              readOnly: true
      volumes:
        - name: certs-volume
          secret:
            secretName: ssl-sebrae