apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-ingressroute
  namespace: traefik
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`domains.com`)
    services:
    - kind: TraefikService
      name: api@internal
  tls:
    secretName: ssl-sebrae
