apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: traefik-dashboard-ingress
  namespace: traefik
spec:
  ingressClassName: traefik
  tls:
    - secretName: ssl-sebrae
      hosts:
        - traefik-dashboard.rr.sebrae.com.br
  rules:
    - host: traefik-dashboard.rr.sebrae.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: traefik-dashboard-service
                port:
                  number: 443
