apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-ingressroute
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.rr.sebrae.com.br`)
      kind: Rule
      services:
        - name: traefik-dashboard-service
          port: 80
  tls:
    secretName: ssl-sebrae
