apiVersion: v1
kind: Service
metadata:
  name: conecta-busines-service
  namespace: conectabiz-homolog
spec:
  type: LoadBalancer
  selector:
    app: conectabiz
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
