apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: redis
spec:
  type: LoadBalancer
  selector:
    app: sebraedocs
  ports:
    - name: http
      port: 6379
      targetPort: 6379
