apiVersion: v1
kind: Service
metadata:
  name: sebraedocs-service
  namespace: sebraedocs
spec:
  type: LoadBalancer
  selector:
    app: sebraedocs
  ports:
    - name: http
      port: 80
      targetPort: 8000
