apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-jucerr
  namespace: consulta-jucerr-homolog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consulta-jucerr
  template:
    metadata:
      labels:
        app: consulta-jucerr
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: apache-facilita
          image: harbor.rr.sebrae.com.br/consulta-jucerr-homolog/consulta-jucerr:v1.0.1
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: SCRIPT_NAME
              value: script.sh
            - name: SERVER_NAME
              value: 10.23.6.29

