apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulta-jucerr
  namespace: consulta-jucerr-homolog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: consulta-jucerr
  template:
    metadata:
      labels:
        app: consulta-jucerr
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
        - name: consulta-jucerr
          image: harbor.rr.sebrae.com.br/consulta-juce-rr-homolog/consulta-juce-rr:v1.2.103
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: SCRIPT_NAME
              value: script-ssl.sh
          volumeMounts:
            - name: laravel-env-volume
              mountPath: /var/www/html/.env
              subPath: .env
          volumeMounts:
            - name: tls-secret
              mountPath: /etc/ssl/certs
              readOnly: true
            - name: laravel-env-volume
              mountPath: /var/www/html/.env
              subPath: .env
      volumes:
        - name: laravel-env-volume
          configMap:
            name: laravel-staging-env
        - name: tls-secret
          secret:
            secretName: ssl-sebrae
