apiVersion: v1
kind: Service
metadata:
  name: consulta-jucerr-service
  namespace: consulta-jucerr-homolog
spec:
  type: LoadBalancer
  selector:
    app: consulta-jucerr
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port : 443
      targetPort: 443
