---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-ubuntu
spec:
  service_type: LoadBalancer
  loadbalancer_ip: '10.23.6.24'
  loadbalancer_protocol: https
  loadbalancer_port: 443
  postgres_configuration_secret: secret-pgsql
  bundle_cacert_secret: ssl-sebrae-custom-certs