---
apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx-ubuntu
spec:
  service_type: LoadBalancer
  loadbalancer_ip: '10.23.6.24'
  loadbalancer_protocol: http
  loadbalancer_port: 80
  postgres_configuration_secret: secret-pgsql
