apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-indexer-pv
  labels:
    app: wazuh-indexer
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wazuh-storage
  volumeMode: Filesystem
  hostPath:
    path: /data/wazuh-indexer
  
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rrsrvworker
