apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-worker-wazuh-manager-worker-1-pv
  labels:
    app: wazuh-manager
    node-type: worker
spec:
  capacity:
    storage: 500Mi  
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wazuh-storage
  local:
    path: /mnt/disks/wazuh-manager-worker-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - rrsrvworker
