apiVersion: v1
kind: PersistentVolume
metadata:
  name: wazuh-manager-worker-pv
  labels:
    app: wazuh-manager
    node-type: master
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: wazuh-storage
  volumeMode: Filesystem
  hostPath:
    path: /data/wazuh-manager-worker
