apiVersion: v1
kind: Service
metadata:
  name: facilita-service
  namespace: facilita-prod
spec:
  type: LoadBalancer
  selector:
    app: facilita
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
